logging:
  level:
    com.cozycodr.ticket_support: DEBUG
    org.springframework: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: it-support
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
  datasource:
    url: jdbc:postgresql://localhost:5432/support_ticket_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  show-actuator: false
  packages-to-scan: com.cozycodr.ticket_support.controller
